### ISSUE TITLE
pysemtec.org is down

### ISSUE THREAD

**Issue by blokhin** [pysemtec/pysemtec.org#1]
I recommend to bind pysemtec.org DNS with this repository.

**Comment by blokhin** [comment]
NB also the name pysem.tech is very sexy and costs just €8 yearly.

**Comment by cknoll** [comment]
Thanks very much for the ping! :+1: .

The problem was that I ignored mails from `do-not-reply@domain-robot.org` because they looked very much like spam that tries to trick you into "verifying" you email address. However it turns out in this case the request was legitimate.

Lesson learned: The ICANN requires email-verification for .com / .info / .net / .org / .name domains and sends mails which might be easily confused with spam.

The domain is reachable again so I close this issue.

wrt. * pysem.tech* sounds nice. However, I prefer pysemtec.org because its pronunciation is less ambiguous as "tech"  could be "tek" or "tesh" (at least in German), and *.tech* is less known and thus IMHO not as easy to remember.

BTW: Do you want to join the gh-org and the mailinglist?

**Comment by blokhin** [comment]
@cknoll sure, will be happy to be in gh-org + mailing list
